=== sdeora17/Web-Stack-Development-Project/XML Lab Exercises/SportsType.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT SPORTS_DOMAIN (SPORTS,FIELDS,HOSTS,BOOKINGS,PLAYERS,SELF-EXERCISES)>

<!ELEMENT SPORTS (SPORT+)>
<!ELEMENT SPORT (SNAME,EQUIPMENTS,GUIDELINES)>
<!ELEMENT SNAME (#PCDATA)>
<!ELEMENT EQUIPMENTS (#PCDATA)>
<!ELEMENT GUIDELINES (#PCDATA)>

<!ELEMENT FIELDS (FIELD+)>
<!ELEMENT FIELD (FNAME,MINIMUM_PLAYERS,TOTAL_PLAYERS,DIMENSION,BASEPRICE,PRICE,LOCATION)>
<!ELEMENT FNAME (#PCDATA)>
<!ELEMENT MINIMUM_PLAYERS (#PCDATA)>
<!ELEMENT TOTAL_PLAYERS (#PCDATA)>
<!ELEMENT DIMENSION (#PCDATA)>
<!ELEMENT BASE-PRICE (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>
<!ELEMENT LOCATION (#PCDATA)>


<!ELEMENT SELF-EXERCISES (SELF-EXERCISE+)>
<!ELEMENT SELF-EXERCISE (EXERCISE_NAME,PRECAUTIONS,DURATION,SET)>

<!ELEMENT EXERCISE_NAME (#PCDATA)>
<!ELEMENT PRECAUTIONS (#PCDATA)>
<!ELEMENT DURATION (#PCDATA)>
<!ELEMENT SET (#PCDATA)>

<!ELEMENT HOSTS (HOST+)>
<!ELEMENT HOST (HOSTNAME,PHONE_NUMBER)>
<!ELEMENT HOSTNAME (#PCDATA)>
<!ELEMENT PHONE_NUMBER (#PCDATA)>

<!ELEMENT BOOKINGS (BOOKING+)>
<!ELEMENT BOOKING (DATE,STIME,ETIME,BASEPRICE,AMOUNT)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT STIME (#PCDATA)>
<!ELEMENT ETIME (#PCDATA)>
<!ELEMENT BASEPRICE (#PCDATA)>
<!ELEMENT AMOUNT (#PCDATA)>

<!ELEMENT PLAYERS (PLAYER+)>
<!ELEMENT PLAYER (PNAME,PAGE)>
<!ELEMENT PNAME (#PCDATA)>
<!ELEMENT PAGE (#PCDATA)>

<!ATTLIST SPORT SID ID #REQUIRED>
<!ATTLIST FIELD FID ID #REQUIRED>
<!ATTLIST HOST HID ID #REQUIRED>
<!ATTLIST BOOKING BID ID #REQUIRED>
<!ATTLIST PLAYER PID ID #REQUIRED>
<!ATTLIST SELF-EXERCISE SEID ID #REQUIRED>

=== sdeora17/Web-Stack-Development-Project/XML Lab Exercises/SportsDomain.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE SPORTS_DOMAIN SYSTEM "SportsType.dtd"[
<!ENTITY guideline_01  "ENTER THE FIELD 10 MINS BEFORE THE STARTING TIME ">
<!ENTITY guideline_02 "WEAR YOUR EQUIPMENTS PROPERLY ">
<!ENTITY guideline_03 "PLAY WILL ONLY TAKE PLACE IF MINIMUM PLAYERS ARE REGISTERED ">
<!ENTITY baseprice "100">
<!ENTITY numberOfGames "0">
<!ENTITY precautions_0 "DO NOT PERFORM EXERCISES IF YOU ARE FEELING ILL">
<!ENTITY precautions_1 "SPEAK TO YOUR DOCTOR IF YOU FACE ANY BREATHING PROBLEMS">
<!ENTITY advice "TAKE PROPER REST BETWEEN SETS BEFORE PERFORMING THE NEXT">

  ]>
<!-- <!ENTITY guideline_01  "ENTER THE FIELD 10 MINS BEFORE THE STARTING TIME"> -->


<SPORTS_DOMAIN>
  <SPORTS>
    <SPORT SID="S01">
      <SNAME>FOOTBALL</SNAME>
      <EQUIPMENTS>SHIN PADS,LONG SOCKS,SHORTS WITH NO POCKETS</EQUIPMENTS>
      <GUIDELINES>&guideline_01;&guideline_02;&guideline_03;</GUIDELINES>
    </SPORT>
    <SPORT SID="S02">
      <SNAME>BASKETBALL</SNAME>
      <EQUIPMENTS>HALF PANTS WITH NO POCKETS,BASKETBALL SHOES</EQUIPMENTS>
      <GUIDELINES>&guideline_01;&guideline_02;&guideline_03;</GUIDELINES>
    </SPORT>
    <SPORT SID="S03">
      <SNAME>CRICKET</SNAME>
      <EQUIPMENTS>GLOVES,HELMET,ABDOMINAL GUARD,RUNNING SHOES</EQUIPMENTS>
      <GUIDELINES>&guideline_01;&guideline_02;&guideline_03;</GUIDELINES>
    </SPORT>
  </SPORTS>

  <FIELDS>
    <FIELD FID="F01">
        <FNAME>SPORTHOOD BEGUR</FNAME>
        <MINIMUM_PLAYERS>10</MINIMUM_PLAYERS>
        <TOTAL_PLAYERS>14</TOTAL_PLAYERS>
        <DIMENSION>50*30 METRES</DIMENSION>
        <BASEPRICE>&baseprice;</BASEPRICE>
        <PRICE>250</PRICE>
        <LOCATION>BEGUR</LOCATION>
    </FIELD>
    <FIELD FID="F02">
      <FNAME>SPORTHOOD HSR LAYOUT</FNAME>
      <MINIMUM_PLAYERS>8</MINIMUM_PLAYERS>
      <TOTAL_PLAYERS>14</TOTAL_PLAYERS>
      <DIMENSION>50*50</DIMENSION>
      <BASEPRICE>100</BASEPRICE>
      <PRICE>250</PRICE>
      <LOCATION>HSR LAYOUT</LOCATION>
  </FIELD>
  <FIELD FID="F03">
    <FNAME>TIGER 5</FNAME>
    <MINIMUM_PLAYERS>16</MINIMUM_PLAYERS>
    <TOTAL_PLAYERS>22</TOTAL_PLAYERS>
    <DIMENSION>40*30</DIMENSION>
    <BASEPRICE>125</BASEPRICE>
    <PRICE>300</PRICE>
    <LOCATION>SG PALYA</LOCATION>
</FIELD>
  </FIELDS>
  
  <HOSTS>
    
    <HOST HID="H01">
      <HOSTNAME>ATUL</HOSTNAME>
      <PHONE_NUMBER>98564</PHONE_NUMBER>
    </HOST>
    
    <HOST HID="H02">
      <HOSTNAME>DHEERAJ</HOSTNAME>
      <PHONE_NUMBER>93512</PHONE_NUMBER>
    </HOST>
    
    <HOST HID="HO3">
      <HOSTNAME>LOKESH</HOSTNAME>
      <PHONE_NUMBER>896712</PHONE_NUMBER>
    </HOST>
  </HOSTS>


  <BOOKINGS>
    <BOOKING BID="B01">
      <DATE>12/07/23</DATE>
      <STIME>9:30</STIME>
      <ETIME>11:30</ETIME>
      <BASEPRICE>&baseprice;</BASEPRICE>
      <AMOUNT>300</AMOUNT>
    </BOOKING>
    <BOOKING BID="BO2">
      <DATE>14/07/23</DATE>
      <STIME>18:30</STIME>
      <ETIME>22:30</ETIME>
      <BASEPRICE>&baseprice;</BASEPRICE>
      <AMOUNT>350</AMOUNT>
    </BOOKING>
    <BOOKING BID="B03">
      <DATE>18/08/23</DATE>
      <STIME>20:30</STIME>
      <ETIME>21:30</ETIME>
      <BASEPRICE>&baseprice;</BASEPRICE>
      <AMOUNT>400</AMOUNT>
    </BOOKING>
  </BOOKINGS>
  
  <PLAYERS>
    <PLAYER PID="P01">
      <PNAME>SIDDHANT</PNAME>
      <PAGE>24</PAGE>
    </PLAYER>
    <PLAYER PID="P02">
      <PNAME>RAMESH</PNAME>
      <PAGE>27</PAGE>
    </PLAYER>
  </PLAYERS>
  
  <SELF-EXERCISES>
    <SELF-EXERCISE SEID="SE01">
      <EXERCISE_NAME>HIGH KNEES</EXERCISE_NAME>
      <PRECAUTIONS>&precautions_0;&precautions_1;</PRECAUTIONS>
      <DURATION>30-45 SECONDS</DURATION>
      <SET>3</SET>
    </SELF-EXERCISE>
    <SELF-EXERCISE SEID="SE02">
      <EXERCISE_NAME>CHEST JUMPS</EXERCISE_NAME>
      <PRECAUTIONS>&precautions_0;&precautions_1;</PRECAUTIONS>
      <DURATION>7-8 REPS</DURATION>
      <SET>3</SET>
    </SELF-EXERCISE>
    <SELF-EXERCISE SEID="SE03">
      <EXERCISE_NAME>PUSH-UPS</EXERCISE_NAME>
      <PRECAUTIONS>&precautions_0;&precautions_1;</PRECAUTIONS>
      <DURATION>30-45 SECONDS</DURATION>
      <SET>3</SET>
    </SELF-EXERCISE>
    
    
  </SELF-EXERCISES>
  
</SPORTS_DOMAIN>
