=== sdeora17/Web-Stack-Development-Project/XML Lab Exercises/SportsSchema_01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.example.org/SportsSchema"
  xmlns:tns="https://www.example.org/SportsSchema"
  elementFormDefault="qualified">

  <xs:element name="SPORTS_DOMAIN" type="tns:sportstype"/>
  <xs:complexType name="sportstype">
    <xs:sequence>
      <xs:element name="SPORTS_TYPE" type="tns:sporttype" maxOccurs="unbounded"></xs:element>
    
      <xs:element name="FIELD_DOMAIN" type="tns:fieldtype" maxOccurs="unbounded"></xs:element>

      <xs:element name="HOST_TYPE" type="tns:hosttype" maxOccurs="unbounded"></xs:element>

      <xs:element name="BOOKING_TYPE" type="tns:bookingtype" maxOccurs="unbounded"></xs:element>
  
      <xs:element name="PLAYER_TYPE" type="tns:playertype" maxOccurs="unbounded"></xs:element>

      <xs:element name="SELF_EXERCISE_TYPE" type="tns:self_exercise_type" maxOccurs="unbounded"></xs:element>

    </xs:sequence>
  </xs:complexType>



<xs:complexType name="sporttype" >

  <xs:sequence>
    <xs:element name="SNAME" type="xs:string" ></xs:element>
    <xs:element name="EQUIPMENTS" type="xs:string"></xs:element>
    <xs:element name="GUIDELINES" type="xs:string"></xs:element>
  </xs:sequence>
  
  <xs:attribute name="SID" type="xs:ID" use="required"></xs:attribute>

</xs:complexType>

<xs:complexType name="fieldtype">
  <xs:sequence>
    <xs:element name="FNAME" type="xs:string"></xs:element>
    <xs:element name="MINIMUM_PLAYERS">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="10"></xs:minInclusive>
          <xs:maxInclusive value="22"></xs:maxInclusive>
        </xs:restriction>      
      </xs:simpleType>
    </xs:element>
    
    <xs:element name="TOTAL_PLAYERS" type="xs:integer"></xs:element>
    <xs:element name="DIMENSION" type="xs:string"></xs:element>
    <xs:element name="BASE-PRICE" type="xs:integer"></xs:element>
    <xs:element name="PRICE" type="xs:integer"></xs:element>
    <xs:element name="LOCATION" type="xs:string"></xs:element>
  </xs:sequence>

  <xs:attribute name="FID" type="xs:ID" use="required"></xs:attribute>
</xs:complexType>

<xs:complexType name="hosttype">
  <xs:sequence>
    <xs:element name="hostname" type="xs:string"></xs:element>
    <xs:element name="phone_number" type="xs:string"></xs:element>
  </xs:sequence>

  <xs:attribute name="HID" type="xs:ID" use="required"></xs:attribute>
</xs:complexType>

<xs:complexType name="bookingtype">
  <xs:sequence>
    <xs:element name="DATE" type="xs:string" ></xs:element>
    <xs:element name="STIME" type="xs:string" ></xs:element>
    <xs:element name="ETIME" type="xs:string" ></xs:element>
    <xs:element name="BASEPRICE" type="xs:string" ></xs:element>
    <xs:element name="AMOUNT" type="xs:string" ></xs:element>
  </xs:sequence>

  <xs:attribute name="BID" type="xs:ID" use="required"></xs:attribute>
</xs:complexType>

<xs:complexType name="playertype">
  <xs:sequence>
    <xs:element name="PNAME" type="xs:string"></xs:element>
    <xs:element name="AGE" type="xs:integer"></xs:element>
  </xs:sequence>

  <xs:attribute name="PID" type="xs:ID" use="required"></xs:attribute>
</xs:complexType>

<xs:complexType name="self_exercise_type">
  <xs:sequence>
    <xs:element name="EXERCISE_NAME" type="xs:string"></xs:element>
    <xs:element name="PRECAUTIONS" type="xs:string">

    </xs:element>
    <xs:element name="DURATION" type="xs:string"></xs:element>
    <xs:element name="SET">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="3"></xs:minInclusive>
          <xs:maxInclusive value="5"></xs:maxInclusive>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="SEID" type="xs:ID" use="required"></xs:attribute>
</xs:complexType>


</xs:schema>

=== sdeora17/Web-Stack-Development-Project/XML Lab Exercises/Sports_Domain_01.xml
<?xml version="1.0" encoding="UTF-8"?>

<SPORTS_DOMAIN xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://www.example.org/SportsSchema"
               xsi:schemaLocation="https://www.example.org/SportsSchema SportsSchema_01.xsd">


  
    <SPORTS_TYPE SID="S01">
    <SNAME>FOOTBALL</SNAME>
    <EQUIPMENTS>SHIN PADS, LONG SOCKS, SHORTS WITH NO POCKETS</EQUIPMENTS>
    <GUIDELINES>ENTER THE FIELD 10 MINS BEFORE THE STARTING TIME, WEAR YOUR EQUIPMENTS PROPERLY, PLAY WILL ONLY TAKE PLACE IF MINIMUM PLAYERS ARE REGISTERED</GUIDELINES>
  </SPORTS_TYPE>
  <SPORTS_TYPE SID="S02">
    <SNAME>BASKETBALL</SNAME>
    <EQUIPMENTS>HALF PANTS WITH NO POCKETS, BASKETBALL SHOES</EQUIPMENTS>
    <GUIDELINES>ENTER THE FIELD 10 MINS BEFORE THE STARTING TIME, WEAR YOUR EQUIPMENTS PROPERLY, PLAY WILL ONLY TAKE PLACE IF MINIMUM PLAYERS ARE REGISTERED</GUIDELINES>
  </SPORTS_TYPE>
  <SPORTS_TYPE SID="S03">
    <SNAME>CRICKET</SNAME>
    <EQUIPMENTS>GLOVES, HELMET, ABDOMINAL GUARD, RUNNING SHOES</EQUIPMENTS>
    <GUIDELINES>ENTER THE FIELD 10 MINS BEFORE THE STARTING TIME, WEAR YOUR EQUIPMENTS PROPERLY, PLAY WILL ONLY TAKE PLACE IF MINIMUM PLAYERS ARE REGISTERED</GUIDELINES>
  </SPORTS_TYPE>

  <FIELD_DOMAIN FID="F01">
    <FNAME>SPORTHOOD BEGUR</FNAME>
    <MINIMUM_PLAYERS>10</MINIMUM_PLAYERS>
    <TOTAL_PLAYERS>14</TOTAL_PLAYERS>
    <DIMENSION>50*30 METRES</DIMENSION>
    <BASE-PRICE>100</BASE-PRICE>
    <PRICE>250</PRICE>
    <LOCATION>BEGUR</LOCATION>
  </FIELD_DOMAIN>
  <FIELD_DOMAIN FID="F02">
    <FNAME>SPORTHOOD HSR LAYOUT</FNAME>
    <MINIMUM_PLAYERS>11</MINIMUM_PLAYERS>
    <TOTAL_PLAYERS>14</TOTAL_PLAYERS>
    <DIMENSION>50*50 METRES</DIMENSION>
    <BASE-PRICE>100</BASE-PRICE>
    <PRICE>250</PRICE>
    <LOCATION>HSR LAYOUT</LOCATION>
  </FIELD_DOMAIN>
  <FIELD_DOMAIN FID="F03">
    <FNAME>TIGER 5</FNAME>
    <MINIMUM_PLAYERS>16</MINIMUM_PLAYERS>
    <TOTAL_PLAYERS>22</TOTAL_PLAYERS>
    <DIMENSION>40*30 METRES</DIMENSION>
    <BASE-PRICE>125</BASE-PRICE>
    <PRICE>300</PRICE>
    <LOCATION>SG PALYA</LOCATION>
  </FIELD_DOMAIN>

  <HOST_TYPE HID="H01">
    <hostname>ATUL</hostname>
    <phone_number>98564</phone_number>
  </HOST_TYPE>
  <HOST_TYPE HID="H02">
    <hostname>DHEERAJ</hostname>
    <phone_number>93512</phone_number>
  </HOST_TYPE>
  <HOST_TYPE HID="H03">
    <hostname>LOKESH</hostname>
    <phone_number>896712</phone_number>
  </HOST_TYPE>

  <BOOKING_TYPE BID="B01">
    <DATE>12/07/23</DATE>
    <STIME>9:30</STIME>
    <ETIME>11:30</ETIME>
    <BASEPRICE>100</BASEPRICE>
    <AMOUNT>300</AMOUNT>
  </BOOKING_TYPE>
  <BOOKING_TYPE BID="B02">
    <DATE>14/07/23</DATE>
    <STIME>18:30</STIME>
    <ETIME>22:30</ETIME>
    <BASEPRICE>100</BASEPRICE>
    <AMOUNT>350</AMOUNT>
  </BOOKING_TYPE>
  <BOOKING_TYPE BID="B03">
    <DATE>18/08/23</DATE>
    <STIME>20:30</STIME>
    <ETIME>21:30</ETIME>
    <BASEPRICE>100</BASEPRICE>
    <AMOUNT>400</AMOUNT>
  </BOOKING_TYPE>

  <PLAYER_TYPE PID="P01">
    <PNAME>SIDDHANT</PNAME>
    <AGE>24</AGE>
  </PLAYER_TYPE>
  <PLAYER_TYPE PID="P02">
    <PNAME>RAMESH</PNAME>
    <AGE>27</AGE>
  </PLAYER_TYPE>

  <SELF_EXERCISE_TYPE SEID="SE01">
    <EXERCISE_NAME>HIGH KNEES</EXERCISE_NAME>
    <PRECAUTIONS>DO NOT PERFORM EXERCISES IF YOU ARE FEELING ILL, SPEAK TO YOUR DOCTOR IF YOU FACE ANY BREATHING PROBLEMS</PRECAUTIONS>
    <DURATION>30-45 SECONDS</DURATION>
    <SET>3</SET>
  </SELF_EXERCISE_TYPE>
  <SELF_EXERCISE_TYPE SEID="SE02">
    <EXERCISE_NAME>CHEST JUMPS</EXERCISE_NAME>
    <PRECAUTIONS>DO NOT PERFORM EXERCISES IF YOU ARE FEELING ILL, SPEAK TO YOUR DOCTOR IF YOU FACE ANY BREATHING PROBLEMS</PRECAUTIONS>
    <DURATION>7-8 REPS</DURATION>
    <SET>3</SET>
  </SELF_EXERCISE_TYPE>
  <SELF_EXERCISE_TYPE SEID="SE03">
    <EXERCISE_NAME>PUSH-UPS</EXERCISE_NAME>
    <PRECAUTIONS>DO NOT PERFORM EXERCISES IF YOU ARE FEELING ILL, SPEAK TO YOUR DOCTOR IF YOU FACE ANY BREATHING PROBLEMS</PRECAUTIONS>
    <DURATION>30-45 SECONDS</DURATION>
    <SET>3</SET>
  </SELF_EXERCISE_TYPE>

</SPORTS_DOMAIN>
